apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.svc.name" . }}
  labels:
  {{- include "goatvote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.type }}
  selector:
    app: backend
    {{- include "goatvote.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.backend.ports | toYaml | nindent 2 }}
