apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goatvote.fullname" . }}-pgdata
  labels:
  {{- include "goatvote.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.pgdata.storageRequest | quote }}
