apiVersion: v1
kind: Service
metadata:
  name: {{ include "goatvote.fullname" . }}-postgres
  labels:
  {{- include "goatvote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.type }}
  selector:
    app: postgres
    {{- include "goatvote.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.postgres.ports | toYaml | nindent 2 }}
