apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goatvote.fullname" . }}-postgres-secret
  labels:
    app: goatvote
  {{- include "goatvote.labels" . | nindent 4 }}
stringData:
  POSTGRES_DB: {{ required "postgresSecret.postgresDb is required" .Values.postgresSecret.postgresDb
    | quote }}
  POSTGRES_PASSWORD: {{ required "postgresSecret.postgresPassword is required" .Values.postgresSecret.postgresPassword
    | quote }}
  POSTGRES_USER: {{ required "postgresSecret.postgresUser is required" .Values.postgresSecret.postgresUser
    | quote }}
