apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: goat
  labels:
    app: goatvote
stringData:
  POSTGRES_DB: goatvote
  POSTGRES_USER: goatuser
  POSTGRES_PASSWORD: goatpass
