api:
  api:
    env:
      postgresHost: postgres
      postgresPort: "5432"
    image:
      repository: goatvote/api
      tag: 1.0.0
    imagePullPolicy: IfNotPresent
  ports:
  - port: 9000
    targetPort: 9000
  replicas: 2
  type: ClusterIP
backend:
  backend:
    env:
      apiUrl: http://api:9000
      databaseUrl: postgresql://goatuser:goatpass@postgres:5432/goatvote
    image:
      repository: goatvote/backend
      tag: 1.0.0
    imagePullPolicy: IfNotPresent
  ports:
  - port: 8000
    targetPort: 8000
  replicas: 2
  type: ClusterIP
frontend:
  frontend:
    image:
      repository: goatvote/frontend
      tag: 1.0.0
    imagePullPolicy: IfNotPresent
  ports:
  - port: 80
    targetPort: 80
  replicas: 1
  type: LoadBalancer
kubernetesClusterDomain: cluster.local
postgres:
  ports:
  - port: 5432
    targetPort: 5432
  postgres:
    image:
      repository: postgres
      tag: 16-alpine
  replicas: 1
  type: ClusterIP
  volumeClaims:
    pgdata:
      requests:
        storage: 1Gi
postgresSecret:
  postgresDb: ""
  postgresPassword: ""
  postgresUser: ""
pvc:
  pgdata:
    storageRequest: 1Gi
