version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: goatvote
      POSTGRES_USER: goatuser
      POSTGRES_PASSWORD: goatpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      API_URL: http://api:9000
      POSTGRES_DB: goatvote
    ports:
      - "8000:8000"

  api:
    build: ./api
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: goatvote
      POSTGRES_USER: goatuser
      POSTGRES_PASSWORD: goatpass
    ports:
      - "9000:9000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  pgdata:

